from django import forms

class NuevoIngreso(forms.Form):
    estudianteRegular = forms.BooleanField()
    Nombre = forms.CharField()
    PrimerApellido = forms.CharField()
    SegundoApellido = forms.CharField()
    Nacionalidad = forms.CharField()
    correo = forms.EmailField()
    cedula = forms.CharField()
    provincia = forms.CharField()
    canton = forms.CharField()
    distrito = forms.CharField()
    direccion = forms.CharField()
    tel = forms.CharField()
    cel = forms.CharField()
    dob = forms.DateField()
    estadoCivil = forms.ChoiceField()
    fotoCedula = forms.FileField()
    fotoTitulo = forms.FileField()
    foto = forms.FileField()
    Grado = forms.ChoiceField()
    Carrera = forms.CharField()
    CantidadMaterias = forms.ChoiceField()
    listaCursos = forms.ChoiceField()
    comprobantePago = forms.FileField()
    acepto = forms.BooleanField()
    
class EstudianteRegular(forms.Form):
    estudianteRegular = forms.BooleanField()
    Nombre = forms.CharField()
    PrimerApellido = forms.CharField()
    SegundoApellido = forms.CharField()
    correo = forms.EmailField()
    cedula = forms.CharField()
    Grado = forms.ChoiceField()
    Carrera = forms.CharField()
    CantidadMaterias = forms.ChoiceField()
    listaCursos = forms.ChoiceField()
    comprobantePago = forms.FileField()
    acepto = forms.BooleanField()